apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wpdb
  labels:
    app: wpdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpdb
  template:
    metadata:
      labels:
        app: wpdb
    spec:
      containers:
      - image: mariadb
        name: wpdb

---

apiVersion: v1
kind: Service
metadata:
  name: wpdb
spec:
  ports:
    - port: 3306
  type: ClusterIP
  selector:
    app: wpdb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wpweb
  labels:
    app: wpweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpweb
  template:
    metadata:
      labels:
        app: wpweb
    spec:
      containers:
      - image: wordpress
        name: wpweb

---

apiVersion: v1
kind: Service
metadata:
  name: wpweb
spec:
  ports:
    - port: 80
  type: LoadBalancer
  selector:
    app: wpweb
